### ISSUE TITLE
Docker image 2.29.1 cant run wiremock.jar

### ISSUE THREAD

**Issue by andrei-oksentyk** [holomekc/wiremock#16]
wiremock version: 2.29.1

The error message on start container: `Error: Invalid or corrupt jarfile /home/wiremock/wiremock.jar`

Config in docker-compose: 
```yaml
version: '3'
services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
     ......
  stubs-wiremock:
    image: "holomekc/wiremock-gui:latest"
    container_name: stubs-wiremock
    ports:
      - "8070:8070"
    volumes:
      - "./test/fixtures/wiremock-stubs:/home/wiremock/storage/mappings"
    environment:
      WIREMOCK_OPTIONS: "--port=8070,--max-request-journal=1000,--local-response-templating,--root-dir=/home/wiremock/storage"
    depends_on:
      - web-app
```

Command to start `docker-compose up &`

There are no issues with previous versions
