### ISSUE TITLE
Malformed js and css files in container version 2.29.1

### ISSUE THREAD

**Issue by ayevee** [holomekc/wiremock#17]
Running  holomekc/wiremock-gui:2.29.1 (or latest) I cannot access the web GUI - an empty page is 

Upon investigating I found out that several files requested by the browser upon intial page load are being sent malformed (data reception stops on timeout):
* assets/ace/ace.js
* styles.1a5fb6c76de0dd58769e.css
* scripts.0002a5aec5f205af7aa2.js
* main.f164b1cd1c09c0e0d1a5.js

The problem is present in Firefox, Chrome, Edge and IE.

If I roll back to previous container version (e.g. 2.27.2.1) GUI works fine (but some of the feature that I'm using in wiremock itself do not work)

**Comment by holomekc** [comment]
Hi sorry for the very, very late answer. I cannot reproduce this:
![image](https://user-images.githubusercontent.com/30546982/148707084-a87e3942-2c03-4f5c-802f-b747852d21cf.png)

Maybe clear your cache? Also I am preparing a new version. Maybe this helps you? The build process is a bit different because wiremock moved from travis to github actions.

How did you run it via docker or did you download the standalone?

**Comment by ayevee** [comment]
> How did you run it via docker or did you download the standalone?
Via docker

> Maybe clear your cache?
I've tried everything (cleared cachem opened in "Private" mode, openned in different browser, openned on different machine) - the issue is always present.

> Also I am preparing a new version. Maybe this helps you?
Sure, I'll be happy to try it out. Please let me know when it's ready.

**Comment by holomekc** [comment]
2.32.0 tag in docker is available now

**Comment by holomekc** [comment]
Did the new version help you? Or do you need further support?

**Comment by ayevee** [comment]
@holomekc, sorry couldn't test earlier.

I've just updated my image to freshly pulled holomekc/wiremock-gui:2.32.0 image and the issue is still present.

**Comment by holomekc** [comment]
Hi :(
For me it works:
![image](https://user-images.githubusercontent.com/30546982/150184044-946a8394-1059-4cde-af0c-529c58e32815.png)

Can you please send me the docker command you are using? I tried with absolute minimum, so just port mapping and it is working fine.
```
docker run -p "8080:8080" holomekc/wiremock-gui:2.32.0
```

Also tested in Chrome, Edge and Firefox.

**Comment by ayevee** [comment]
I'm using docker-compose, here is the extract of yaml config:
```yaml
  wiremock:
    image: holomekc/wiremock-gui:2.32.0
    ports:
      - ${PORT_PREFIX}00:8088
      - ${PORT_PREFIX}01:8443
    # Wiremock External Requests
      - 29902:8088
    environment:
      WIREMOCK_OPTIONS: "--port=8088,--https-port=8443,--max-request-journal=1000,--global-response-templating,--root-dir=/home/wiremock/storage"
    networks:
      common:
        aliases:
          - wiremock
    volumes:
      - ./wiremock_data:/home/wiremock/storage
```

`PORT_PREFIX` environment variable is defined in accompanying `.env` file:
```sh
PORT_PREFIX=200
```
