### ISSUE TITLE
[Kubernetes] service-service-host is not a recognized option

### ISSUE THREAD

**Issue by MatheusGeiger** [holomekc/wiremock#35]
Hello! I'm trying to test the `holomekc/wiremock-gui:latest` on my Kubernetes (linux machine OS) and I have an error when I use images with the version above than `"holomekc/wiremock-gui:2.32.0.2"`. 

This version workings "holomekc/wiremock-gui:2.32.0.2" fine but the lasts versions or up to this version raise an unexpected error `service-service-host is not a recognized option`

for this print for example I'm using a `holomekc/wiremock-gui:latest` image
<img width="1440" alt="mock" src="https://user-images.githubusercontent.com/22987079/227608093-dc56b67b-c7c7-4d68-81af-7ea3a4ffaccd.png">

when I use the wire mock image without UI the services stay running without errors 
<img width="1440" alt="mock_2" src="https://user-images.githubusercontent.com/22987079/227608132-91b27783-466c-415b-9c1a-e3b0e0620078.png">

how the wiremock image is working properly has led me to believe it's something with the ui pack but I haven't been able to dig into the background of what could be causing this error.

Have you already gone through this or do you know of a way for us to identify the cause of the bug/problem?

these are the receipts without UI:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock
  namespace: production
  labels:
    app.kubernetes.io/name: wiremock
    app.kubernetes.io/instance: wiremock
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wiremock
      app.kubernetes.io/instance: wiremock
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wiremock
        app.kubernetes.io/instance: wiremock
    spec:
      containers:
        - name: wiremock
          image: "wiremock/wiremock:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
```

and this is with UI:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock
  namespace: production
  labels:
    app.kubernetes.io/name: wiremock
    app.kubernetes.io/instance: wiremock
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wiremock
      app.kubernetes.io/instance: wiremock
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wiremock
        app.kubernetes.io/instance: wiremock
    spec:
      containers:
        - name: wiremock
          image: "holomekc/wiremock-gui:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
```

literally only the images changes and one work and another not.

I tried a lot of recipe combinations, it even worked locally on my mac but on Linux I couldn't.

complete receipt with attempts
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock
  namespace: production
  labels:
    app.kubernetes.io/name: wiremock
    app.kubernetes.io/instance: wiremock
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wiremock
      app.kubernetes.io/instance: wiremock
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wiremock
        app.kubernetes.io/instance: wiremock
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
#      volumes:
#        - name: wiremock-data-storage-mappings
#          persistentVolumeClaim:
#            claimName: wiremock-claim
#        - name: extension-data-volume
#          emptyDir: {}
      containers:
        - name: wiremock
          image: "holomekc/wiremock-gui:latest"
#          image: "holomekc/wiremock-gui:2.32.0.2"
#          image: "wiremock/wiremock:latest"
          imagePullPolicy: IfNotPresent
#          env:
#            - name: WIREMOCK_PORT
#              value: "9021"
#            - name: WIREMOCK_MAX_REQUEST_JOURNAL
#              value: "1000"
#            - name: WIREMOCK_LOCAL_RESPONSE_TEMPLATING
#              value: ""
#            - name: WIREMOCK_ROOT_DIR
#              value: /home/wiremock/storage
#            - name: WIREMOCK_EXTENSIONS
#              value: org.wiremock.webhooks.Webhooks
#            - name: WIREMOCK_OPTIONS
#              value: "--port=9021,--max-request-journal=1000,--local-response-templating,--root-dir=/home/wiremock/storage, --extensions=org.wiremock.webhooks.Webhooks"
#          command: ["java", "-cp", "/home/wiremock/wiremock.jar", "com.github.tomakehurst.wiremock.standalone.WireMockServerRunner"]
          ports:
            - containerPort: 8080
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /__admin/webapp
#              port: 9021
#              scheme: HTTP
#          readinessProbe:
#            httpGet:
#              path: /__admin/webapp
#              port: 9021
#              scheme: HTTP
#          volumeMounts:
#            - mountPath: /home/wiremock/storage/mappings
#              name: wiremock-data-storage-mappings
#            - mountPath: /home/wiremock/extensions
#              name: extension-data-volume
#      initContainers:
#      - name: download-webhook-extension
#        image: "bash:5"
#        imagePullPolicy: IfNotPresent
#        command: ["bash", "-c", "mkdir -p /home/wiremock/extensions && wget https://repo1.maven.org/maven2/org/wiremock/wiremock-webhooks-extension/2.35.0/wiremock-webhooks-extension-2.35.0.jar -P /home/wiremock/extensions/"]
#        volumeMounts:
#          - mountPath: /home/wiremock/extensions
#            name: extension-data-volume
```

**Comment by MatheusGeiger** [comment]
I can see the error by looking for the code and debugging the behavior. 

When I deploy into cluster Kubernetes using service, deployment, and other resources, the default behavior of Kubernetes is to create environments to facilitate the orchestration of all services.
The name os variables are composed of receipt instructions like name os services + container port. I can see many of these automatic environment in container execution.

<img width="1230" alt="Screenshot 2023-03-24 at 15 43 44" src="https://user-images.githubusercontent.com/22987079/227616689-b056694e-2ce0-4e38-b547-2607ea161687.png">


On my situation the name of my service the service name was `wiremock`

service 
```yaml
apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: wiremock-service
spec:
  selector:
    app.kubernetes.io/name: wiremock
    app.kubernetes.io/instance: wiremock
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 9021
```
with these receipt parameters and Kubernetes behavior I can see many environments with the prefix `WIREMOCK``

```shell
wiremock@apimock-59794f875b-2k4pj:~$ env | grep WIREMOCK
WIREMOCK_SERVICE_SERVICE_PORT_HTTP=8080
WIREMOCK_SERVICE_PORT_8080_TCP_PORT=8080
WIREMOCK_SERVICE_PORT=tcp://172.20.78.5:8080
WIREMOCK_SERVICE_PORT_8080_TCP=tcp://172.20.78.5:8080
WIREMOCK_SERVICE_SERVICE_HOST=172.20.78.5
WIREMOCK_SERVICE_SERVICE_PORT=8080
WIREMOCK_SERVICE_PORT_8080_TCP_PROTO=tcp
WIREMOCK_SERVICE_PORT_8080_TCP_ADDR=172.20.78.5
```

looking at the code of [WireMockServerRunner.java](https://github.com/holomekc/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/standalone/WireMockServerRunner.java#L65) the line 65 get all environment values with `key.startsWith("WIREMOCK_"` and make a parses then create an options parameter fo `.jar` command.

In my situation, the kubernetes automatic environments are sent to `.jar` with `options` but these values are not allowed then we can see the error mentioned.

To fix this I changed my service receipt and deployment name to `mockapi`

```yaml
apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: apimock-service
spec:
  selector:
    app.kubernetes.io/name: apimock
    app.kubernetes.io/instance: apimock
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 9021
```

and these changes resolve my problem and the UI and wiremock work correctly.
